version: '3'
services:
  node_app:
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_new
    
    ports:
      - "1337:1337"  # Map the local port to the container port
    depends_on:
      - postgres  # Depend on the PostgreSQL service

  postgres:
    image: postgres:latest
    networks:
      - backend
    container_name: postgres
    environment:
      POSTGRES_DB: strapi-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"  # Map the local PostgreSQL port to the container port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  backend:
